name: npm-test

on:
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: '16'
      cache: 'npm'
  - uses: browser-actions/setup-chrome@latest
  - run: chrome --version
  - run: npm install
  - run: npm copy-fonts
  - run: npm run build
  - run: npm run test
